services:
  kavita:
    image: jvmilazz0/kavita:0.8.9@sha256:1f2acae7466d022f037ea09f7989eb7c487f916b881174c7a6de33dbfa8acb39
    restart: always
    environment:
      TZ: Europe/Berlin
    volumes:
      - ${DIRECTORY}/books:/books
      - ${DIRECTORY}/config:/kavita/config
    labels:
      - net.unraid.docker.managed=dockhand
      - net.unraid.docker.webui=https://${DOMAIN}
      - net.unraid.docker.icon=https://cdn.jsdelivr.net/gh/selfhst/icons/webp/kavita.webp
      - traefik.enable=true
      - traefik.http.routers.kavita.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.kavita.entrypoints=https
      - traefik.http.routers.kavita.tls=true
      - traefik.http.routers.kavita.tls.certresolver=desec
    expose:
      - 5000
    networks:
      - proxy

networks:
  proxy:
    external: true
