services:
  silverbullet:
    image: ghcr.io/silverbulletmd/silverbullet:2.8.1@sha256:c5f99879153d9e89025b2a9d6b76a0927935bd71c06d66f3a7ad60fc77621c6d
    restart: always
    environment:
      SB_USER: admin:password
    volumes:
      - ${DIRECTORY}:/space
    labels:
      - net.unraid.docker.managed=dockhand
      - net.unraid.docker.webui=https://${DOMAIN}
      - net.unraid.docker.icon=https://cdn.jsdelivr.net/gh/selfhst/icons/webp/silverbullet.webp
      - traefik.enable=true
      - traefik.http.routers.silverbullet.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.silverbullet.entrypoints=https
    expose:
      - 3000
    networks:
      - proxy

networks:
  proxy:
    external: true
