services:
  pocket-id:
    image: ghcr.io/pocket-id/pocket-id:v2.18.0@sha256:323e7ef5bfacf7cf32f22f3d10ccdf48e0c97c94d67e7e40b0b996830deb5165
    restart: always
    logging:
      options:
        max-size: 5m
        max-file: '2'
    deploy:
      resources:
        limits:
          memory: '256M'
          cpus: '0.5'
    environment:
      APP_URL: https://${DOMAIN}
      TRUST_PROXY: true
      PUID: 1000
      PGID: 1000
      ANALYTICS_DISABLED: true
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
    volumes:
      - ${DIRECTORY}:/app/data
    ports:
      - ${PORT:-1411}:1411
