services:
  pocket-id:
    image: ghcr.io/pocket-id/pocket-id:v2.13.0@sha256:c9c1d7b70006968d673a1073df048a3fdec73ccb54e182320b56bb911340f6f1
    restart: always
    deploy:
      resources:
        limits:
          memory: '256M'
          cpus: '0.5'
    environment:
      APP_URL: https://${DOMAIN}
      TRUST_PROXY: true
      PUID: 1000
      PGID: 1000
      ANALYTICS_DISABLED: true
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
    volumes:
      - ${DIRECTORY}:/app/data
    labels:
      - net.unraid.docker.managed=dockhand
      - net.unraid.docker.webui=https://${DOMAIN}
      - net.unraid.docker.icon=https://cdn.jsdelivr.net/gh/selfhst/icons/webp/pocket-id.webp
      - traefik.enable=true
      - traefik.http.routers.pocket-id.entrypoints=https
      - traefik.http.routers.pocket-id.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.pocket-id.tls=true
      - traefik.http.routers.pocket-id.tls.certresolver=desec
      - traefik.http.services.pocket-id.loadbalancer.server.port=1411
    expose:
      - 1411
    networks:
      - proxy

networks:
  proxy:
    external: true
