services:
  pdf:
    image: ghcr.io/alam00000/bentopdf:2.4.0@sha256:a6e8ea0ff59c0154f7e54f28e0fac4b28b03e0c57fe67d2d79fdeab8b90805ff
    container_name: pdf
    restart: always
    environment:
      TZ: Europe/Berlin
    labels:
      - net.unraid.docker.managed=dockhand
      - net.unraid.docker.webui=https://${DOMAIN}
      - net.unraid.docker.icon=https://cdn.jsdelivr.net/gh/selfhst/icons/webp/bentopdf.webp
      - traefik.enable=true
      - traefik.http.routers.pdf.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.pdf.entrypoints=https
      - traefik.http.routers.pdf.tls=true
      - traefik.http.routers.pdf.tls.certresolver=desec
    expose:
      - 8080
    networks:
      - proxy

networks:
  proxy:
    external: true
