services:
  pdf:
    image: ghcr.io/alam00000/bentopdf:2.6.0@sha256:96709a7ecd64a3fb4adf4dcf320808248a565993ea0c67febd25da12a34dcab7
    container_name: pdf
    restart: always
    environment:
      TZ: Europe/Berlin
    labels:
      - net.unraid.docker.managed=dockhand
      - net.unraid.docker.webui=https://${DOMAIN}
      - net.unraid.docker.icon=https://cdn.jsdelivr.net/gh/selfhst/icons/webp/bentopdf.webp
      - traefik.enable=true
      - traefik.http.routers.pdf.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.pdf.entrypoints=https
      - traefik.http.routers.pdf.tls=true
      - traefik.http.routers.pdf.tls.certresolver=desec
    expose:
      - 8080
    networks:
      - proxy

networks:
  proxy:
    external: true
