services:
  pdf:
    image: ghcr.io/alam00000/bentopdf:2.3.3@sha256:391b68d5eba09e8cce255ffb438d5696c5d249f20a603d3129da83a317a2dd0d
    container_name: pdf
    restart: always
    environment:
      TZ: Europe/Berlin
    labels:
      - net.unraid.docker.managed=dockhand
      - net.unraid.docker.webui=https://${DOMAIN}
      - net.unraid.docker.icon=https://cdn.jsdelivr.net/gh/selfhst/icons/webp/bentopdf.webp
      - traefik.enable=true
      - traefik.http.routers.pdf.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.pdf.entrypoints=https
      - traefik.http.routers.pdf.tls=true
      - traefik.http.routers.pdf.tls.certresolver=desec
    expose:
      - 8080
    networks:
      - proxy

networks:
  proxy:
    external: true
