services:
  actual-budget:
    image: actualbudget/actual-server:26.9.0@sha256:552beab3dec8c93d46b8b9245612d63c3f123b8a45063a474f53e229b17621d3
    restart: always
    deploy:
      resources:
        limits:
          memory: '512M'
          cpus: '0.5'
    volumes:
      - ${DIRECTORY}:/data
    labels:
      - net.unraid.docker.managed=dockhand
      - net.unraid.docker.webui=https://${DOMAIN}
      - net.unraid.docker.icon=https://cdn.jsdelivr.net/gh/selfhst/icons/webp/actual-budget.webp
      - traefik.enable=true
      - traefik.http.routers.actual-budget.entrypoints=https
      - traefik.http.routers.actual-budget.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.actual-budget.tls=true
      - traefik.http.routers.actual-budget.tls.certresolver=hetzner
    healthcheck:
      test: ['CMD-SHELL', 'node scripts/health-check.js']
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 20s
    expose:
      - 5006
    networks:
      - proxy

networks:
  proxy:
    external: true
