services:
  actual-budget:
    image: actualbudget/actual-server:26.8.1@sha256:6478d9ddfc0924479c09e6699c205e354c6f2216dfe7de3c0fb7b590d6edcdc5
    restart: always
    deploy:
      resources:
        limits:
          memory: '512M'
          cpus: '0.5'
    volumes:
      - ${DIRECTORY}:/data
    labels:
      - net.unraid.docker.managed=dockhand
      - net.unraid.docker.webui=https://${DOMAIN}
      - net.unraid.docker.icon=https://cdn.jsdelivr.net/gh/selfhst/icons/webp/actual-budget.webp
      - traefik.enable=true
      - traefik.http.routers.actual-budget.entrypoints=https
      - traefik.http.routers.actual-budget.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.actual-budget.tls=true
      - traefik.http.routers.actual-budget.tls.certresolver=desec
    healthcheck:
      test: ['CMD-SHELL', 'node scripts/health-check.js']
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 20s
    expose:
      - 5006
    networks:
      - proxy

networks:
  proxy:
    external: true
