services:
  leafwiki:
    image: ghcr.io/perber/leafwiki:v0.11.1@sha256:7f2949f733c17c081d3fbda9050b88baf915abd6704ad82d620c491335457d8f
    restart: always
    user: 1000:1000
    environment:
      LEAFWIKI_JWT_SECRET: ${JWT_SECRET}
      LEAFWIKI_ADMIN_PASSWORD: admin
    volumes:
      - ${DIRECTORY}:/app/data
    labels:
      - net.unraid.docker.managed=dockhand
      - net.unraid.docker.webui=https://${DOMAIN}
      - net.unraid.docker.icon=https://cdn.jsdelivr.net/gh/selfhst/icons/webp/leafwiki.webp
      - traefik.enable=true
      - traefik.http.routers.leafwiki.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.leafwiki.entrypoints=https
      - traefik.http.routers.leafwiki.tls=true
      - traefik.http.routers.leafwiki.tls.certresolver=desec
    expose:
      - 8080
    networks:
      - proxy

networks:
  proxy:
    external: true
