services:
  leafwiki:
    image: ghcr.io/perber/leafwiki:v0.11.0@sha256:e1b4b62b074deeb72fa3dea7256dbed79b9baa0a0ce46d4d8d1e4d16bf5653ea
    restart: always
    user: 1000:1000
    environment:
      LEAFWIKI_JWT_SECRET: ${JWT_SECRET}
      LEAFWIKI_ADMIN_PASSWORD: admin
    volumes:
      - ${DIRECTORY}:/app/data
    labels:
      - net.unraid.docker.managed=dockhand
      - net.unraid.docker.webui=https://${DOMAIN}
      - net.unraid.docker.icon=https://cdn.jsdelivr.net/gh/selfhst/icons/webp/leafwiki.webp
      - traefik.enable=true
      - traefik.http.routers.leafwiki.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.leafwiki.entrypoints=https
      - traefik.http.routers.leafwiki.tls=true
      - traefik.http.routers.leafwiki.tls.certresolver=desec
    expose:
      - 8080
    networks:
      - proxy

networks:
  proxy:
    external: true
