services:
  leafwiki:
    image: ghcr.io/perber/leafwiki:v0.10.2@sha256:0589893b8ac5d71a56090b7c1a51322abf829968f45a1e1bee2e2050d659572c
    restart: always
    user: 1000:1000
    environment:
      LEAFWIKI_JWT_SECRET: ${JWT_SECRET}
      LEAFWIKI_ADMIN_PASSWORD: admin
    volumes:
      - ${DIRECTORY}:/app/data
    labels:
      - net.unraid.docker.managed=dockhand
      - net.unraid.docker.webui=https://${DOMAIN}
      - net.unraid.docker.icon=https://cdn.jsdelivr.net/gh/selfhst/icons/webp/leafwiki.webp
      - traefik.enable=true
      - traefik.http.routers.leafwiki.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.leafwiki.entrypoints=https
      - traefik.http.routers.leafwiki.tls=true
      - traefik.http.routers.leafwiki.tls.certresolver=desec
    expose:
      - 8080
    networks:
      - proxy

networks:
  proxy:
    external: true
