services:
  gatus:
    image: twinproduction/gatus:v5.36.0@sha256:c5f210d095fa78e6efaa20ffeb14803f2ba4f10615e16a6d12087697149617f0
    restart: always
    deploy:
      resources:
        limits:
          memory: '1G'
          cpus: '1.0'
    volumes:
      - ${DIRECTORY}/config:/config
      - ${DIRECTORY}/data:/data/
    labels:
      - net.unraid.docker.managed=dockhand
      - net.unraid.docker.webui=https://${DOMAIN}
      - net.unraid.docker.icon=https://cdn.jsdelivr.net/gh/selfhst/icons/webp/gatus.webp
      - traefik.enable=true
      - traefik.http.routers.gatus.entrypoints=https
      - traefik.http.routers.gatus.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.gatus.tls=true
      - traefik.http.routers.gatus.tls.certresolver=hetzner
    expose:
      - 8080
    networks:
      - proxy

networks:
  proxy:
    external: true
