services:
  gatus:
    image: twinproduction/gatus:v5.37.0@sha256:094eb186e55235db367e90e9d56140e5897b7044c41de23cde4cc18e6da1242e
    restart: always
    logging:
      options:
        max-size: 5m
        max-file: '2'
    deploy:
      resources:
        limits:
          memory: '1G'
          cpus: '1.0'
    volumes:
      - ${DIRECTORY}/config:/config
      - ${DIRECTORY}/data:/data/
    labels:
      - net.unraid.docker.managed=dockhand
      - net.unraid.docker.webui=https://${DOMAIN}
      - net.unraid.docker.icon=https://cdn.jsdelivr.net/gh/selfhst/icons/webp/gatus.webp
      - traefik.enable=true
      - traefik.http.routers.gatus.entrypoints=https
      - traefik.http.routers.gatus.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.gatus.tls=true
      - traefik.http.routers.gatus.tls.certresolver=hetzner
    expose:
      - 8080
    networks:
      - proxy

networks:
  proxy:
    external: true
