services:
  vaultwarden:
    image: vaultwarden/server:1.37.3@sha256:1587c45feaa479f1f5e8af3b00eded36bff77bcf1880cf8dbf0541706dd470e0
    restart: always
    logging:
      options:
        max-size: 5m
        max-file: '2'
    deploy:
      resources:
        limits:
          memory: '256M'
          cpus: '0.5'
    volumes:
      - ${DIRECTORY}/data:/data
    labels:
      - net.unraid.docker.managed=dockhand
      - net.unraid.docker.webui=https://${DOMAIN}
      - net.unraid.docker.icon=https://cdn.jsdelivr.net/gh/selfhst/icons/webp/vaultwarden.webp
      - traefik.enable=true
      - traefik.http.routers.vaultwarden.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.vaultwarden.entrypoints=https
      - traefik.http.routers.vaultwarden.tls=true
      - traefik.http.routers.vaultwarden.tls.certresolver=hetzner
    expose:
      - 80
    networks:
      - proxy

networks:
  proxy:
    external: true
