services:
  vaultwarden:
    image: vaultwarden/server:1.35.5@sha256:b0be02bdc08fde3ce253d01be2b5bf9ba0add2ae6f029fbacc096fd65af0a2b8
    container_name: vaultwarden
    restart: always
    volumes:
      - ${DIRECTORY}/data:/data
    labels:
      - net.unraid.docker.managed=dockhand
      - net.unraid.docker.webui=https://${DOMAIN}
      - net.unraid.docker.icon=https://cdn.jsdelivr.net/gh/selfhst/icons/webp/vaultwarden.webp
      - traefik.enable=true
      - traefik.http.routers.vaultwarden.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.vaultwarden.entrypoints=https
    expose:
      - 80
    networks:
      - proxy

networks:
  proxy:
    external: true
