services:
  vaultwarden:
    image: vaultwarden/server:1.35.7@sha256:9a8eec71f4a52411cc43edc7a50f33e9b6f62b5baca0dd95f0c6e7fd60f1a341
    container_name: vaultwarden
    restart: always
    volumes:
      - ${DIRECTORY}/data:/data
    labels:
      - net.unraid.docker.managed=dockhand
      - net.unraid.docker.webui=https://${DOMAIN}
      - net.unraid.docker.icon=https://cdn.jsdelivr.net/gh/selfhst/icons/webp/vaultwarden.webp
      - traefik.enable=true
      - traefik.http.routers.vaultwarden.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.vaultwarden.entrypoints=https
    expose:
      - 80
    networks:
      - proxy

networks:
  proxy:
    external: true
