services:
  bookstack:
    image: lscr.io/linuxserver/bookstack:25.12.20251224@sha256:597cd4fc121f1d74c40e93cf7b0d5e1b3fc61af486a87cd65e2f86b0c0a5d914
    container_name: bookstack
    restart: always
    depends_on:
      bookstack-db:
        condition: service_healthy
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Berlin
      APP_URL: https://${DOMAIN}
      APP_KEY: ${APP_KEY}
      DB_HOST: bookstack-db
      DB_PORT: 3306
      DB_USERNAME: user
      DB_PASSWORD: password
      DB_DATABASE: db
      MAIL_DRIVER: smtp
      MAIL_HOST: smtp.gmail.com
      MAIL_PORT: 587
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_ENCRYPTION: tls
      MAIL_FROM_ADDRESS: ${MAIL_FROM_ADDRESS}
      MAIL_FROM_NAME: ${MAIL_FROM_NAME}
    volumes:
      - ${DIRECTORY}:/config
    labels:
      - net.unraid.docker.managed=dockhand
      - net.unraid.docker.webui=https://${DOMAIN}
      - net.unraid.docker.icon=https://cdn.jsdelivr.net/gh/selfhst/icons/webp/bookstack.webp
      - traefik.enable=true
      - traefik.http.routers.bookstack.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.bookstack.entrypoints=https
    expose:
      - 80
    networks:
      - proxy
      - net

  bookstack-db:
    image: mariadb:10.11.16@sha256:8d9046cdb0b0961b3d2119bcb4bea62a185f11944be5968bc42b81d47801902e
    container_name: bookstack-db
    restart: always
    healthcheck:
      test: ['CMD', '/usr/local/bin/healthcheck.sh', '--connect', '--mariadbupgrade', '--innodb_initialized']
      interval: 20s
      start_period: 30s
      timeout: 5s
      retries: 10
    environment:
      TZ: Europe/Berlin
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_LOG_CONSOLE: true
      MARIADB_AUTO_UPGRADE: 1
    volumes:
      - db:/var/lib/mysql
    labels:
      - net.unraid.docker.managed=dockhand
      - net.unraid.docker.icon=https://cdn.jsdelivr.net/gh/selfhst/icons/webp/mariadb.webp
    expose:
      - 3306
    networks:
      - net

networks:
  proxy:
    external: true
  net:
    external: false

volumes:
  db: {}
