services:
  ntfy:
    image: binwiederhier/ntfy:v2.22.0@sha256:d8b3408c75d5ae78e03339af6103e7e6195e56573eea6f1ad34bb4dc4f44f340
    container_name: ntfy
    restart: always
    command:
      - serve
    environment:
      TZ: Europe/Berlin
    volumes:
      - ${DIRECTORY}/cache:/var/cache/ntfy
      - ${DIRECTORY}/ntfy:/etc/ntfy
    labels:
      - net.unraid.docker.managed=dockhand
      - net.unraid.docker.webui=https://${DOMAIN}
      - net.unraid.docker.icon=https://cdn.jsdelivr.net/gh/selfhst/icons/webp/ntfy.webp
      - traefik.enable=true
      - traefik.http.routers.ntfy.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.ntfy.entrypoints=https
      - traefik.http.routers.ntfy.tls=true
      - traefik.http.routers.ntfy.tls.certresolver=desec
    expose:
      - 80
    networks:
      - proxy

networks:
  proxy:
    external: true
