services:
  gocron:
    image: ghcr.io/flohoss/gocron:v0.10.0@sha256:e25ed9e894f32359f83220d570b11504efa30929438eaca96c604b560d42a15a
    restart: always
    hostname: gobackup
    extra_hosts:
      - '${EXTRA_HOSTS:-localhost:127.0.0.1}'
    deploy:
      resources:
        limits:
          memory: '1G'
          cpus: '1.0'
    volumes:
      - ${DIRECTORY}/config:/app/config/
      - ${DIRECTORY}/.resticpwd:/secrets/.resticpwd
      - ${DIRECTORY}/.rclone.conf:/root/.config/rclone/rclone.conf
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DATA_MOUNT}
    labels:
      - net.unraid.docker.managed=dockhand
      - net.unraid.docker.icon=https://cdn.jsdelivr.net/gh/selfhst/icons/webp/restic.webp
    ports:
      - 8156:8156
