services:
  gocron:
    image: ghcr.io/flohoss/gocron:v0.13.2@sha256:18f5a8cb5ce557c0e76d4651d0bf9826a87018ac82dc83f782716146599f51ab
    restart: always
    logging:
      options:
        max-size: 5m
        max-file: '2'
    hostname: gobackup
    extra_hosts:
      - '${EXTRA_HOSTS:-localhost:127.0.0.1}'
    deploy:
      resources:
        limits:
          memory: '1G'
          cpus: '1.0'
    volumes:
      - ${DIRECTORY}/config:/app/config/
      - ${DIRECTORY}/.resticpwd:/secrets/.resticpwd
      - ${DIRECTORY}/.rclone.conf:/root/.config/rclone/rclone.conf
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DATA_MOUNT}
    labels:
      - net.unraid.docker.managed=dockhand
      - net.unraid.docker.icon=https://cdn.jsdelivr.net/gh/selfhst/icons/webp/restic.webp
    ports:
      - 8156:8156
