services:
  forgejo:
    image: codeberg.org/forgejo/forgejo:16.0.0@sha256:9b8f02e896b1151ea60da05cf3e11fc7bd1c432dc6becee75ceb420f3d162b97
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      FORGEJO__service__ENABLE_INTERNAL_SIGNIN: false
      FORGEJO__database__DB_TYPE: postgres
      FORGEJO__database__HOST: db:5432
      FORGEJO__database__NAME: db
      FORGEJO__database__USER: user
      FORGEJO__database__PASSWD: password
      FORGEJO__security__REVERSE_PROXY_TRUSTED_PROXIES: ${TRUSTED_PROXIES:-172.18.0.0/16}
    volumes:
      - ${DIRECTORY}/data:/data
    labels:
      - net.unraid.docker.managed=dockhand
      - net.unraid.docker.webui=https://${DOMAIN}
      - net.unraid.docker.icon=https://cdn.jsdelivr.net/gh/selfhst/icons/webp/forgejo.webp
      - traefik.enable=true
      - traefik.http.routers.forgejo.entrypoints=https
      - traefik.http.routers.forgejo.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.forgejo.tls=true
      - traefik.http.routers.forgejo.tls.certresolver=desec
      - traefik.http.routers.forgejo.service=forgejo
      - traefik.http.services.forgejo.loadbalancer.server.port=3000
    expose:
      - 3000
    ports:
      - '30:22'
    networks:
      - proxy
      - net

  db:
    image: postgres:17.10@sha256:a426e44bac0b759c95894d68e1a0ac03ecc20b619f498a91aae373bf06d8508d
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U user -d db']
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db:/var/lib/postgresql/data
    labels:
      - backup.target=${BACKUP_TARGET:-forgejo}
      - net.unraid.docker.managed=dockhand
      - net.unraid.docker.icon=https://cdn.jsdelivr.net/gh/selfhst/icons/webp/postgresql.webp
    expose:
      - 5432
    networks:
      - net

networks:
  proxy:
    external: true
  net:
    external: false

volumes:
  data: {}
  db: {}
