services:
  traefik:
    image: traefik:v3.7.14@sha256:575fa15b135078fe5e50aa847987d96dbddd7b093c172429618404df73f3fa7c
    restart: always
    logging:
      options:
        max-size: 50m
        max-file: '7'
    deploy:
      resources:
        limits:
          memory: '1G'
          cpus: '1.0'
    command: >
      --api.dashboard=true
      --api.insecure=true
      --global.checkNewVersion=false
      --global.sendAnonymousUsage=false
      --entrypoints.http.address=:80
      --entrypoints.http.http.redirections.entryPoint.to=https
      --entrypoints.https.address=:443
      --entrypoints.https.transport.respondingTimeouts.readTimeout=600s
      --entrypoints.https.transport.respondingTimeouts.idleTimeout=600s
      --entrypoints.https.transport.respondingTimeouts.writeTimeout=600s
      --entrypoints.https.http.encodedCharacters.allowEncodedSlash=true
      --entrypoints.https.http.encodedCharacters.allowEncodedQuestionMark=true
      --entrypoints.https.http.middlewares=security-headers@file
      --entrypoints.https.http.tls.certresolver=hetzner
      --providers.providersThrottleDuration=2s
      --providers.file.watch=true
      --providers.file.directory=/etc/traefik/config
      --providers.docker=true
      --providers.docker.exposedbydefault=false
      --providers.docker.network=proxy
      --certificatesresolvers.hetzner.acme.email=${PRIVATE_EMAIL}
      --certificatesresolvers.hetzner.acme.storage=/etc/traefik/acme.json
      --certificatesresolvers.hetzner.acme.keytype=EC384
      --certificatesresolvers.hetzner.acme.dnschallenge.provider=hetzner
      --certificatesresolvers.hetzner.acme.dnschallenge.resolvers=hydrogen.ns.hetzner.com:53,oxygen.ns.hetzner.com:53
      --certificatesresolvers.hetzner.acme.dnschallenge.propagation.disableanschecks=true
      --certificatesresolvers.hetzner.acme.dnschallenge.delaybeforecheck=120
      --log.level=ERROR
      --serversTransport.insecureSkipVerify=true
      ${TRAEFIK_EXTRA_FLAGS:-}
    environment:
      BOUNCER_KEY: ${BOUNCER_KEY}
      HETZNER_API_TOKEN: ${HETZNER_API_TOKEN}
      HETZNER_TTL: '60'
    volumes:
      - ${DIRECTORY}:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - net.unraid.docker.managed=dockhand
      - net.unraid.docker.icon=https://cdn.jsdelivr.net/gh/selfhst/icons/webp/traefik.webp
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    networks:
      - proxy

networks:
  proxy:
    external: true

# Example EXTRA_FLAGS:
# --entrypoints.https.http.tls.domains[0].main=*.unjx.de
# --providers.docker.defaultRule="Host(`{{ lower (first (splitList \"-\" .Name) | default .Name) }}.unjx.de`)"
