services:
  mittagskarte:
    image: ghcr.io/flohoss/mittagskarte:v1.6.0@sha256:f33f7439061b2eeb770009ddcac3f250daeab03a654df4132a345ec7e5ebc488
    restart: always
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '2.0'
        reservations:
          memory: 1G
          cpus: '1.0'
    environment:
      - TZ=Europe/Berlin
      - EMAIL=${EMAIL}
    volumes:
      - ${DIRECTORY}:/app/data
    labels:
      - net.unraid.docker.managed=dockhand
      - net.unraid.docker.webui=https://${DOMAIN}
      - net.unraid.docker.icon=https://cdn.jsdelivr.net/gh/selfhst/icons/webp/mittagskarte.webp
      - traefik.enable=true
      - traefik.http.routers.mittagskarte.entrypoints=https
      - traefik.http.routers.mittagskarte.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.mittagskarte.tls=true
      - traefik.http.routers.mittagskarte.tls.certresolver=desec
    expose:
      - 8090
    networks:
      - proxy

networks:
  proxy:
    external: true
