services:
  mittagskarte:
    image: ghcr.io/flohoss/mittagskarte:v1.1.0@sha256:2a69473c734699cfd8d518b9e76ab676911d5a5ae2bc3eb39290da72f8b615cb
    container_name: mittagskarte
    restart: always
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'
    volumes:
      - ${DIRECTORY}:/app/data
    labels:
      - net.unraid.docker.managed=dockhand
      - net.unraid.docker.webui=https://${DOMAIN}
      - net.unraid.docker.icon=https://cdn.jsdelivr.net/gh/selfhst/icons/webp/mittagskarte.webp
      - traefik.enable=true
      - traefik.http.routers.mittagskarte.entrypoints=https
      - traefik.http.routers.mittagskarte.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.mittagskarte.tls=true
      - traefik.http.routers.mittagskarte.tls.certresolver=desec
    expose:
      - 8090
    networks:
      - proxy

networks:
  proxy:
    external: true
