services:
  cryptpad:
    image: 'cryptpad/cryptpad:version-2026.5.1@sha256:1f89dcdd28c1375f675e47b1d0cf07a51f3e9a07a79dc93c8cddb3295b98a34d'
    restart: always
    deploy:
      resources:
        limits:
          memory: '1G'
          cpus: '1.0'
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    environment:
      CPAD_MAIN_DOMAIN: https://${DOMAIN}
      CPAD_SANDBOX_DOMAIN: https://${SANDBOX_DOMAIN}
      CPAD_CONF: /cryptpad/config/config.js
      CPAD_INSTALL_ONLYOFFICE: true
    volumes:
      - ${DIRECTORY}/block:/cryptpad/block
      - ${DIRECTORY}/blob:/cryptpad/blob
      - ${DIRECTORY}/customize:/cryptpad/customize
      - ${DIRECTORY}/data:/cryptpad/data
      - ${DIRECTORY}/files:/cryptpad/datastore
      - ${DIRECTORY}/config.js:/cryptpad/config/config.js
      - ${DIRECTORY}/onlyoffice/dist:/cryptpad/www/common/onlyoffice/dist
      - ${DIRECTORY}/onlyoffice/conf:/cryptpad/onlyoffice-conf
    labels:
      - backup.target=${BACKUP_TARGET:-cryptpad}
      - net.unraid.docker.managed=dockhand
      - net.unraid.docker.webui=https://${DOMAIN}
      - net.unraid.docker.icon=https://cdn.jsdelivr.net/gh/selfhst/icons/webp/cryptpad.webp
      - traefik.enable=true
      - traefik.http.routers.cryptpad.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.cryptpad.entrypoints=https
      - traefik.http.routers.cryptpad.tls=true
      - traefik.http.routers.cryptpad.tls.certresolver=desec
      - traefik.http.routers.cryptpad-sandbox.rule=Host(`${SANDBOX_DOMAIN}`)
      - traefik.http.routers.cryptpad-sandbox.entrypoints=https
      - traefik.http.routers.cryptpad-sandbox.tls=true
      - traefik.http.routers.cryptpad-sandbox.tls.certresolver=desec
    expose:
      - 3000
    networks:
      - proxy

networks:
  proxy:
    external: true
