services:
  outline:
    image: outlinewiki/outline:1.8.1@sha256:e224dcbe34670bdae8835c32d5abc692d3560dfa262b72fb7232f4d87185aebd
    restart: always
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      NODE_ENV: production
      URL: https://${DOMAIN}
      SECRET_KEY: ${SECRET_KEY}
      UTILS_SECRET: ${UTILS_SECRET}
      DEFAULT_LANGUAGE: de_DE
      DATABASE_URL: postgres://user:password@db:5432/db
      REDIS_URL: redis://redis:6379
      FORCE_HTTPS: true
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_FROM_EMAIL: ${SMTP_FROM_EMAIL}
      LOG_LEVEL: warn
      PGSSLMODE: disable
      FILE_STORAGE: local
      FILE_STORAGE_LOCAL_ROOT_DIR: /var/lib/outline/data
      FILE_STORAGE_UPLOAD_MAX_SIZE: 20971520
    volumes:
      - ${DIRECTORY}:/var/lib/outline/data
    labels:
      - net.unraid.docker.managed=dockhand
      - net.unraid.docker.webui=https://${DOMAIN}
      - net.unraid.docker.icon=https://cdn.jsdelivr.net/gh/selfhst/icons/webp/outline.webp
      - traefik.enable=true
      - traefik.http.routers.outline.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.outline.entrypoints=https
      - traefik.http.routers.outline.tls=true
      - traefik.http.routers.outline.tls.certresolver=desec
    expose:
      - 3000
    networks:
      - proxy
      - net

  db:
    image: postgres:17.7-alpine3.21@sha256:5bcb5623bb6999b2f7fbd2109f0bfc1f144d138b52ca35ede95d644d93585c2f
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U user -d db']
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db:/var/lib/postgresql/data
    labels:
      - backup.target=${BACKUP_TARGET:-outline}
      - net.unraid.docker.managed=dockhand
      - net.unraid.docker.icon=https://cdn.jsdelivr.net/gh/selfhst/icons/webp/postgresql.webp
    expose:
      - 5432
    networks:
      - net

  redis:
    image: redis:7.4.5-alpine3.21@sha256:bb186d083732f669da90be8b0f975a37812b15e913465bb14d845db72a4e3e08
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli ping || exit 1']
    volumes:
      - redis:/data
    labels:
      - net.unraid.docker.managed=dockhand
      - net.unraid.docker.icon=https://cdn.jsdelivr.net/gh/selfhst/icons/webp/redis.webp
    expose:
      - 6379
    networks:
      - net

networks:
  proxy:
    external: true
  net:
    external: false

volumes:
  db: {}
  redis: {}
