services:
  outline:
    image: outlinewiki/outline:1.9.2@sha256:32d76719c378931dd65d93945930ca380d8376a0337d98a991fcc12b266f33cf
    restart: always
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      NODE_ENV: production
      URL: https://${DOMAIN}
      SECRET_KEY: ${SECRET_KEY}
      UTILS_SECRET: ${UTILS_SECRET}
      DEFAULT_LANGUAGE: de_DE
      DATABASE_URL: postgres://user:password@db:5432/db
      REDIS_URL: redis://redis:6379
      FORCE_HTTPS: true
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_FROM_EMAIL: ${SMTP_FROM_EMAIL}
      LOG_LEVEL: warn
      PGSSLMODE: disable
      FILE_STORAGE: local
      FILE_STORAGE_LOCAL_ROOT_DIR: /var/lib/outline/data
      FILE_STORAGE_UPLOAD_MAX_SIZE: 20971520
    volumes:
      - ${DIRECTORY}:/var/lib/outline/data
    labels:
      - net.unraid.docker.managed=dockhand
      - net.unraid.docker.webui=https://${DOMAIN}
      - net.unraid.docker.icon=https://cdn.jsdelivr.net/gh/selfhst/icons/webp/outline.webp
      - traefik.enable=true
      - traefik.http.routers.outline.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.outline.entrypoints=https
      - traefik.http.routers.outline.tls=true
      - traefik.http.routers.outline.tls.certresolver=desec
    expose:
      - 3000
    networks:
      - proxy
      - net

  db:
    image: postgres:17.10@sha256:a426e44bac0b759c95894d68e1a0ac03ecc20b619f498a91aae373bf06d8508d
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U user -d db']
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db:/var/lib/postgresql/data
    labels:
      - backup.target=${BACKUP_TARGET:-outline}
      - net.unraid.docker.managed=dockhand
      - net.unraid.docker.icon=https://cdn.jsdelivr.net/gh/selfhst/icons/webp/postgresql.webp
    expose:
      - 5432
    networks:
      - net

  redis:
    image: redis:8.8.0@sha256:234c902a2db49461a129e2d4aeff85b28cf20187ed274a67f6e50995fa713c7b
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli ping || exit 1']
    volumes:
      - redis:/data
    labels:
      - net.unraid.docker.managed=dockhand
      - net.unraid.docker.icon=https://cdn.jsdelivr.net/gh/selfhst/icons/webp/redis.webp
    expose:
      - 6379
    networks:
      - net

networks:
  proxy:
    external: true
  net:
    external: false

volumes:
  db: {}
  redis: {}
