services:
  snapotter:
    image: snapotter/snapotter:2.0.0@sha256:de55c9279b067ea0bb5bfc7755dde6f72e727c8e1326629d1fa927cfbe6e3712
    restart: always
    environment:
      TZ: Europe/Berlin
      AUTH_ENABLED: false
      LOG_LEVEL: warn
      DEFAULT_THEME: dark
    volumes:
      - ${DIRECTORY}:/data
    labels:
      - net.unraid.docker.managed=dockhand
      - net.unraid.docker.webui=https://${DOMAIN}
      - net.unraid.docker.icon=https://cdn.jsdelivr.net/gh/selfhst/icons/webp/snapotter.webp
      - traefik.enable=true
      - traefik.http.routers.snapotter.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.snapotter.entrypoints=https
      - traefik.http.routers.snapotter.tls=true
      - traefik.http.routers.snapotter.tls.certresolver=desec
    expose:
      - 8080
    networks:
      - proxy

networks:
  proxy:
    external: true
