services:
  freshrss:
    image: freshrss/freshrss:1.29.1@sha256:ab6b363102ccdbc39f6a62db926f567c61a5289bf25ba460f1c34423d8cc1a4d
    restart: always
    deploy:
      resources:
        limits:
          memory: '256M'
          cpus: '0.5'
    extra_hosts:
      - '${EXTRA_HOSTS:-localhost:127.0.0.1}'
    logging:
      options:
        max-size: 10m
    environment:
      TZ: Europe/Berlin
      BASE_URL: https://${DOMAIN}
      CRON_MIN: '2,32'
      OIDC_ENABLED: 1
      OIDC_PROVIDER_METADATA_URL: ${OIDC_PROVIDER_METADATA_URL}
      OIDC_CLIENT_ID: ${OIDC_CLIENT_ID}
      OIDC_CLIENT_SECRET: ${OIDC_CLIENT_SECRET}
      OIDC_SCOPES: openid email profile
      OIDC_X_FORWARDED_HEADERS: X-Forwarded-Proto X-Forwarded-Host
      OIDC_REMOTE_USER_CLAIM: preferred_username
    volumes:
      - ${DIRECTORY}/data:/var/www/FreshRSS/data
      - ${DIRECTORY}/extensions:/var/www/FreshRSS/extensions
    labels:
      - net.unraid.docker.managed=dockhand
      - net.unraid.docker.webui=https://${DOMAIN}
      - net.unraid.docker.icon=https://cdn.jsdelivr.net/gh/selfhst/icons/webp/freshrss.webp
      - traefik.enable=true
      - traefik.http.routers.freshrss.entrypoints=https
      - traefik.http.routers.freshrss.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.freshrss.tls=true
      - traefik.http.routers.freshrss.tls.certresolver=desec
    expose:
      - 8080
    networks:
      - proxy

networks:
  proxy:
    external: true
