services:
  esphome:
    image: ghcr.io/esphome/esphome:2026.9.0@sha256:f6509fcf917a732fd80058567b237d5b9286b9dc6c8dde1b655fbb69ebd600ad
    restart: always
    logging:
      options:
        max-size: 5m
        max-file: '2'
    deploy:
      resources:
        limits:
          memory: '8G'
          cpus: '4.0'
    environment:
      TZ: Europe/Berlin
      ESPHOME_USERNAME: ${ESPHOME_USERNAME}
      ESPHOME_PASSWORD: ${ESPHOME_PASSWORD}
    volumes:
      - ${DIRECTORY}:/config
      - /etc/localtime:/etc/localtime:ro
    labels:
      - net.unraid.docker.managed=dockhand
      - net.unraid.docker.webui=https://${DOMAIN}
      - net.unraid.docker.icon=https://cdn.jsdelivr.net/gh/selfhst/icons/webp/esphome.webp
      - traefik.enable=true
      - traefik.http.routers.esphome.entrypoints=https
      - traefik.http.routers.esphome.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.esphome.tls=true
      - traefik.http.routers.esphome.tls.certresolver=hetzner
    expose:
      - 6052
    ports:
      - 6055:6055
    networks:
      - proxy

networks:
  proxy:
    external: true
