services:
  esphome:
    image: ghcr.io/esphome/esphome:2026.8.2@sha256:000c5ee5ee96d57208ee48f2d255f73713236f183959803e64cd0b00c39b277b
    restart: always
    deploy:
      resources:
        limits:
          memory: '8G'
          cpus: '4.0'
    environment:
      TZ: Europe/Berlin
      ESPHOME_USERNAME: ${ESPHOME_USERNAME}
      ESPHOME_PASSWORD: ${ESPHOME_PASSWORD}
    volumes:
      - ${DIRECTORY}:/config
      - /etc/localtime:/etc/localtime:ro
    labels:
      - net.unraid.docker.managed=dockhand
      - net.unraid.docker.webui=https://${DOMAIN}
      - net.unraid.docker.icon=https://cdn.jsdelivr.net/gh/selfhst/icons/webp/esphome.webp
      - traefik.enable=true
      - traefik.http.routers.esphome.entrypoints=https
      - traefik.http.routers.esphome.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.esphome.tls=true
      - traefik.http.routers.esphome.tls.certresolver=hetzner
    expose:
      - 6052
    ports:
      - 6055:6055
    networks:
      - proxy

networks:
  proxy:
    external: true
